from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator

User = get_user_model()


class Document(models.Model):
    """Model for uploaded PDF documents"""
    
    STATUS_CHOICES = [
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ]
    
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='documents'
    )
    title = models.CharField(max_length=255)
    file = models.FileField(upload_to='documents/%Y/%m/%d/')
    file_size = models.IntegerField(help_text='File size in bytes')
    pages = models.IntegerField(default=0)
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='processing'
    )
    extracted_text = models.TextField(blank=True, null=True)
    
    # Timestamps
    uploaded_at = models.DateTimeField(auto_now_add=True)
    processed_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-uploaded_at']
        indexes = [
            models.Index(fields=['user', '-uploaded_at']),
            models.Index(fields=['status']),
        ]
    
    def __str__(self):
        return f"{self.title} - {self.user.email}"


class DocumentSummary(models.Model):
    """Model for document summaries generated by Gemini AI"""
    
    document = models.OneToOneField(
        Document,
        on_delete=models.CASCADE,
        related_name='summary'
    )
    content = models.TextField(help_text='Main summary content')
    key_points = models.JSONField(
        default=list,
        help_text='List of key points from the document'
    )
    insights = models.JSONField(
        default=list,
        help_text='Key insights extracted from the document'
    )
    examples = models.JSONField(
        default=list,
        help_text='Examples from the document with descriptions'
    )
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name_plural = 'Document summaries'
    
    def __str__(self):
        return f"Summary for {self.document.title}"


class Flashcard(models.Model):
    """Model for flashcards generated from documents"""
    
    DIFFICULTY_CHOICES = [
        ('easy', 'Easy'),
        ('medium', 'Medium'),
        ('hard', 'Hard'),
    ]
    
    document = models.ForeignKey(
        Document,
        on_delete=models.CASCADE,
        related_name='flashcards'
    )
    question = models.TextField()
    answer = models.TextField()
    difficulty = models.CharField(
        max_length=10,
        choices=DIFFICULTY_CHOICES,
        default='medium'
    )
    order = models.IntegerField(default=0)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['order', 'id']
        indexes = [
            models.Index(fields=['document', 'order']),
        ]
    
    def __str__(self):
        return f"Flashcard {self.order} for {self.document.title}"


class FlashcardSet(models.Model):
    """Model to manage different sets of flashcards for the same document"""
    
    document = models.ForeignKey(
        Document,
        on_delete=models.CASCADE,
        related_name='flashcard_sets'
    )
    name = models.CharField(max_length=100, default='Default Set')
    card_count = models.IntegerField(
        validators=[MinValueValidator(10), MaxValueValidator(40)]
    )
    is_active = models.BooleanField(default=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.name} ({self.card_count} cards) - {self.document.title}"